// src/lib/components/Nav.svelte
<script lang="ts">
import { page } from "$app/state";
</script>

<li>
	<a href="/" class={page.url.pathname === "/" ? "active" : ""}>Webhook</a>
</li>
<li>
	<a href="/metrics" class={page.url.pathname === "/metrics" ? "active" : ""}>
		Metrics
	</a>
</li>
<li>
	<a href="/lgtm" class={page.url.pathname === "/lgtm" ? "active" : ""}>LGTM</a>
</li>

// app/ui/Nav.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

export default function Nav() {
	const pathname = usePathname();
	return (
		<>
			<li>
				<Link href="/" className={pathname === "/" ? "active" : ""}>
					Webhook
				</Link>
			</li>
			<li>
				<Link href="/lgtm" className={pathname === "/lgtm" ? "active" : ""}>
					LGTM
				</Link>
			</li>
		</>
	);
}
