// app/ui/DeleteButton.tsx
import { useRouter } from "next/navigation";
import { type MouseEvent, useCallback, useContext } from "react";
import { deleteFile } from "../lgtm/actions";
import { Context } from "./GlobalContext";

export default function DeleteButton({
	fileName,
	onClick = () => {},
	isVisible = true,
}: { fileName: string; onClick?: () => void; isVisible?: boolean }) {
	const router = useRouter();
	const { setMessage } = useContext(Context);
	const onClickDelete = useCallback(
		async (e: MouseEvent<HTMLButtonElement>) => {
			try {
				e.stopPropagation();
				await deleteFile(fileName);
			} finally {
				router.refresh();
				onClick();
				setMessage("画像削除完了");
			}
		},
		[setMessage, fileName, router, onClick],
	);
	return (
		<button
			type="button"
			className={`btn btn-square absolute right-3 top-20${isVisible ? "" : " invisible group-hover/item:visible"}`}
			onClick={onClickDelete}
		>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				className="h-6 w-6"
				fill="none"
				viewBox="0 0 24 24"
				stroke="currentColor"
			>
				<title>Delete</title>
				<path
					strokeWidth="2"
					d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
				/>
			</svg>
		</button>
	);
}

// src/lib/components/DeleteButton.svelte
<script lang="ts">
import { setMessage } from "$lib/stores/toast.svelte";

let {
	fileName,
	isVisible = true,
	onDeleted,
}: {
	fileName: string;
	isVisible?: boolean;
	onDeleted?: () => void;
} = $props();

async function onClickDelete(e: MouseEvent) {
	e.stopPropagation();
	const res = await fetch("/lgtm/delete", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ fileName }),
	});
	if (res.ok) {
		onDeleted?.();
		setMessage("画像削除完了");
	} else {
		setMessage("画像削除失敗");
	}
}
</script>

<button
	type="button"
	class={`btn btn-square absolute right-3 top-20 ${isVisible ? "" : " invisible group-hover/item:visible"}`}
	onclick={onClickDelete}
>
	<svg
		xmlns="http://www.w3.org/2000/svg"
		class="h-6 w-6"
		fill="none"
		viewBox="0 0 24 24"
		stroke="currentColor"
	>
		<title>Delete</title>
		<path
			stroke-width="2"
			d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
		/>
	</svg>
</button>
